### ISSUE TITLE
Issues with master

### ISSUE THREAD

**Issue by manosbatsis** [corda/token-sdk#10]
Master has a failed test, plus needs version updates to Corda 4.0 and gradle plugins 4.0.41

```bash
manos@sobol:~/git/token-sdk$ ./gradlew  build install

> Task :workflow:test 

com.r3.corda.sdk.token.workflow.TokenFlowTests > create evolvable token, then issue and move FAILED
```

The failed test stacktrace is 

```
java.lang.IllegalStateException: The LinearState with ID 0dcf21fb-7fb1-48ce-b894-c25a523f6f2f is unknown to this node or it has been exited from the ledger.
	at net.corda.core.contracts.LinearPointer.resolve(StatePointer.kt:113)
	at net.corda.core.transactions.TransactionBuilder.resolveStatePointers(TransactionBuilder.kt:530)
	at net.corda.core.transactions.TransactionBuilder.addInputState(TransactionBuilder.kt:584)
	at com.r3.corda.sdk.token.workflow.selection.TokenSelection.generateMove(TokenSelection.kt:213)
	at com.r3.corda.sdk.token.workflow.selection.TokenSelection.generateMove(TokenSelection.kt:135)
	at com.r3.corda.sdk.token.workflow.flows.MoveToken$Initiator.call(MoveToken.kt:60)
	at com.r3.corda.sdk.token.workflow.flows.MoveToken$Initiator.call(MoveToken.kt:25)
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:228)
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:45)
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092)
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788)
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100)
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at net.corda.node.utilities.AffinityExecutor$ServiceAffinityExecutor$1$thread$1.run(AffinityExecutor.kt:63)
```

**Comment by prateektiwari7** [comment]
Hi @manosbatsis 

I am getting the same error. Please check:- 

Flow file has 

```
@InitiatingFlow
@StartableByRPC
class TokenIssue(var name : String,var bal : Int,var party: List<Party>) : FlowLogic<SignedTransaction>() {

    override val progressTracker = ProgressTracker()

    @Suspendable
    override fun call() : SignedTransaction {
        val notary = serviceHub.networkMapCache.notaryIdentities.first()

        
        val house = House(name,ourIdentity,bal,party,10, UniqueIdentifier("testingapplication", java.util.UUID.randomUUID()))

        val housePtr = house.toPointer<House>()

        val houseToken: NonFungibleToken = housePtr issuedBy ourIdentity heldBy  party.get(0)

        subFlow(CreateEvolvableTokens(house withNotary  notary))

        return  subFlow(ConfidentialIssueTokens(listOf(houseToken)))
        
    }
}

@InitiatedBy(TokenIssue::class)
class TokenIssue_Responder(val counterpartySession: FlowSession) : FlowLogic<SignedTransaction>() {
    @Suspendable
    override fun call() : SignedTransaction {
        val signedTransactionFlow = object : SignTransactionFlow(counterpartySession) {
            override fun checkTransaction(stx: SignedTransaction) = requireThat {
                val output = stx.tx.outputs.single().data
            }
        }

        val txWeJustSignedId = subFlow(signedTransactionFlow)
        return subFlow(ReceiveFinalityFlow(counterpartySession, txWeJustSignedId.id))

    }


}
```

State code 

```
@BelongsToContract(HouseContract::class)
data class House(
        val address: String,
        val issuer: Party,
        val valuation: Int,
        override val maintainers: List<Party>,
        override val fractionDigits: Int = 0,
        override val linearId: UniqueIdentifier
) : EvolvableTokenType()
```

Contract code 

`class HouseContract : EvolvableTokenContract(), net.corda.core.contracts.Contract {

    override fun additionalCreateChecks(tx: LedgerTransaction) {
        // Not much to do for this example token.

    }

    override fun additionalUpdateChecks(tx: LedgerTransaction) {

    }
}`


I am getting error as **`java.lang.IllegalStateException: The LinearState with ID 976a42be-2b46-41b6-9882-968d27762434 is unknown to this node or it has been exited from the ledger.`**
