### ISSUE TITLE
DistributionRecord error with 1.1-RC02+ on  Corda Enterprise 4.2 

### ISSUE THREAD

**Issue by manosbatsis** [corda/token-sdk#154]
Upgrading from 1.1-RC01 to 1.1-RC02 or 1.1-RC05* seems to break our cordapps on Corda Enterprise 4.2.

```
java.lang.IllegalArgumentException: Not an entity: class com.r3.corda.lib.tokens.workflows.internal.schemas.DistributionRecord
        at org.hibernate.metamodel.internal.MetamodelImpl.entity(MetamodelImpl.java:536) ~[hibernate-core-5.3.10.Final.jar:5.3.10.Final]
        at org.hibernate.query.criteria.internal.QueryStructure.from(QueryStructure.java:126) ~[hibernate-core-5.3.10.Final.jar:5.3.10.Final]
        at org.hibernate.query.criteria.internal.CriteriaQueryImpl.from(CriteriaQueryImpl.java:153) ~[hibernate-core-5.3.10.Final.jar:5.3.10.Final]
        at com.r3.corda.lib.tokens.workflows.internal.flows.distribution.DistributionUtilitiesKt$getDistributionRecord$1.invoke(DistributionUtilities.kt:39) ~[tokens-workflows-1.1-RC05.jar:?]
        at com.r3.corda.lib.tokens.workflows.internal.flows.distribution.DistributionUtilitiesKt$getDistributionRecord$1.invoke(DistributionUtilities.kt) ~[tokens-workflows-1.1-RC05.jar:?]
        at net.corda.node.internal.AbstractNode$ServiceHubInternalImpl.withEntityManager(AbstractNode.kt:1115) ~[corda-node-4.2.jar:?]
        at com.r3.corda.lib.tokens.workflows.internal.flows.distribution.DistributionUtilitiesKt.getDistributionRecord(DistributionUtilities.kt:36) ~[tokens-workflows-1.1-RC05.jar:?]
        at com.r3.corda.lib.tokens.workflows.internal.flows.distribution.DistributionUtilitiesKt.hasDistributionRecord(DistributionUtilities.kt:50) ~[tokens-workflows-1.1-RC05.jar:?]
        at com.r3.corda.lib.tokens.workflows.utilities.FlowUtilitiesKt.addPartyToDistributionList(FlowUtilities.kt:28) ~[tokens-workflows-1.1-RC05.jar:?]
        at com.r3.corda.lib.tokens.workflows.internal.flows.distribution.DistributionUtilitiesKt.addToDistributionList(DistributionUtilities.kt:70) ~[tokens-workflows-1.1-RC05.jar:?]
        at com.r3.corda.lib.tokens.workflows.internal.flows.distribution.UpdateDistributionListFlow.call(UpdateDistributionListFlow.kt:53) ~[tokens-workflows-1.1-RC05.jar:?]
        at com.r3.corda.lib.tokens.workflows.internal.flows.distribution.UpdateDistributionListFlow.call(UpdateDistributionListFlow.kt:17) ~[tokens-workflows-1.1-RC05.jar:?]
        at net.corda.node.services.statemachine.FlowStateMachineImpl.subFlow(FlowStateMachineImpl.kt:333) ~[corda-node-4.2.jar:?]
        at net.corda.core.flows.FlowLogic.subFlow(FlowLogic.kt:314) ~[corda-core-4.2.jar:?]
        at com.r3.corda.lib.tokens.workflows.flows.issue.IssueTokensFlow.call(IssueTokensFlow.kt:91) ~[tokens-workflows-1.1-RC05.jar:?]
        at com.r3.corda.lib.tokens.workflows.flows.issue.IssueTokensFlow.call(IssueTokensFlow.kt:46) ~[tokens-workflows-1.1-RC05.jar:?]
        at net.corda.node.services.statemachine.FlowStateMachineImpl.subFlow(FlowStateMachineImpl.kt:333) ~[corda-node-4.2.jar:?]
        at net.corda.core.flows.FlowLogic.subFlow(FlowLogic.kt:314) ~[corda-core-4.2.jar:?]

```

**Comment by roger3cev** [comment]
@manosbatsis Hey dude, sorry missed this one! Hmm looks like there might be a schema migration missing for the `DistributionRecord` table. Strange though, as we should have picked this up during testing. Do you mind providing a few more details on your setup? I.e. was it a fresh run or were you upgrading a node with existing data? Cheers

**Comment by manosbatsis** [comment]
Hey @roger3cev thanks for picking this up. Error happens when I update the Tokens SDK version in build.gradle. Is Corda Enteprise 4.3 available already, i.e. will it be released along with OS from now on?

**Comment by kasiastreich** [comment]
Hey @manosbatsis could you provide me startup logs from the node that throws this exception? Also, what database are you using?

**Comment by manosbatsis** [comment]
@roger3cev  sent a log on slack as github complaints for comment size. The error occurs when running  `MockNetwork` tests after i change token SDK's version to `1.1-RC05-PRESIGN`

**Comment by roger3cev** [comment]
Thanks for the logs! @kasiastreich looked into this but couldn't reproduce ... do you have any more info? E.g. corda version used etc..

**Comment by kasiastreich** [comment]
@roger3cev could you send them to me?

**Comment by manosbatsis** [comment]
@roger3cev Corda Enterprise 4.2, @kasiastreich i'll send them to you via slack as well

**Comment by roger3cev** [comment]
Ah this wont work with 4.2 - you need at least 4.3
